// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChYOkydKBL5XQtXi8wIScXs9e6kkRuOf8',
    appId: '1:312790993912:web:744c9b53697ee3d5d0a40d',
    messagingSenderId: '312790993912',
    projectId: 'crud-559c8',
    authDomain: 'crud-559c8.firebaseapp.com',
    storageBucket: 'crud-559c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ6SNJ4Rp4bJ0TvM-DZd1nIRBizxhaZ6Y',
    appId: '1:312790993912:android:8798cf6e4b75b37ed0a40d',
    messagingSenderId: '312790993912',
    projectId: 'crud-559c8',
    storageBucket: 'crud-559c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2pAGuH_2y2VSgdx48QGUrA1nRVWGm9_g',
    appId: '1:312790993912:ios:d3ae065c0747794ad0a40d',
    messagingSenderId: '312790993912',
    projectId: 'crud-559c8',
    storageBucket: 'crud-559c8.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2pAGuH_2y2VSgdx48QGUrA1nRVWGm9_g',
    appId: '1:312790993912:ios:d3ae065c0747794ad0a40d',
    messagingSenderId: '312790993912',
    projectId: 'crud-559c8',
    storageBucket: 'crud-559c8.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChYOkydKBL5XQtXi8wIScXs9e6kkRuOf8',
    appId: '1:312790993912:web:59717c83829b79b4d0a40d',
    messagingSenderId: '312790993912',
    projectId: 'crud-559c8',
    authDomain: 'crud-559c8.firebaseapp.com',
    storageBucket: 'crud-559c8.appspot.com',
  );
}
